environment:
  matrix:
    - CMAKE_BUILD_TYPE: DEBUG
    - CMAKE_BUILD_TYPE: RELEASE

os: Visual Studio 2015

platform:
  - x86
  - x64

init:
  - cmd: set PATH=C:\Program Files (x86)\CMake\bin\;%PATH%

before_build:
  - cmd: IF "%PLATFORM%" == "x64" (cmake -DCMAKE_BUILD_TYPE=%CMAKE_BUILD_TYPE% -G "Visual Studio 14 2015 Win64") ELSE (cmake -DCMAKE_BUILD_TYPE=%CMAKE_BUILD_TYPE%)

build_script:
  - cmake --build . --config %CMAKE_BUILD_TYPE%

after_build:
  - cmd: IF "%APPVEYOR_REPO_TAG%" == "true" (cpack -G WIX -C %CMAKE_BUILD_TYPE%)

test_script:
  - ctest -C %CMAKE_BUILD_TYPE%

artifacts:
  - path: '*.msi'

deploy:
  provider: GitHub
  auth_token:
    secure: AtMhevKUU0Cf+huWpOz+axnd0TdO5fO+m6yjLR34qYKRqdsBIPI508k/sMxDxzLj
  draft: false
  prerelease: false
  force_update: true
  on:
    branch: master
    appveyor_repo_tag: true
    CMAKE_BUILD_TYPE: RELEASE
