language: c

compiler:
  - clang
  - gcc

env:
  - CMAKE_BUILD_TYPE=RELEASE BUILD_SHARED_LIBS=TRUE
  - CMAKE_BUILD_TYPE=RELEASE BUILD_SHARED_LIBS=FALSE
  - CMAKE_BUILD_TYPE=DEBUG BUILD_SHARED_LIBS=TRUE
  - CMAKE_BUILD_TYPE=DEBUG BUILD_SHARED_LIBS=FALSE

before_script:
  - cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS}

script:
  - make
  - make test
