language: c

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

env:
  - CMAKE_BUILD_TYPE=RELEASE
  - CMAKE_BUILD_TYPE=DEBUG

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq valgrind

before_script:
  - cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}

script:
  - make
  - make test
  - find bin -type f -print -exec valgrind --error-exitcode=-1 {} \;
