language: c

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

env:
  - CMAKE_BUILD_TYPE=RELEASE
  - CMAKE_BUILD_TYPE=DEBUG

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  
install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -qq valgrind; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install valgrind; fi

before_script:
  - cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}

script:
  - make
  - make test
  - find bin -type f -print -exec valgrind --error-exitcode=-1 {} \;
