environment:
  matrix:
    - CMAKE_BUILD_TYPE: DEBUG
    - CMAKE_BUILD_TYPE: RELEASE

platform:
  - x86
  - x64

init:
  - cmd: set PATH=C:\Program Files (x86)\CMake\bin\;%PATH%

before_build:
  - cmake .

build_script:
  - cmake --build . --config %CMAKE_BUILD_TYPE%

test_script:
  - ctest -C %CMAKE_BUILD_TYPE%

before_deploy:
  - cpack -G WIX -C %CMAKE_BUILD_TYPE%

deploy:
  release: libtable-v$(appveyor_build_version)
  description: ''
  provider: GitHub
  auth_token:
    secure: AtMhevKUU0Cf+huWpOz+axnd0TdO5fO+m6yjLR34qYKRqdsBIPI508k/sMxDxzLj
  artifact: /.*\.msi/
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
 